# Module 1: Data validation and pre-processing technique

In [1]:
#import library packages
import numpy as n
import pandas as p

In [2]:
#Load given dataset
data = p.read_csv('crop.csv')

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
data.head()

nitrogen  phosphorus  potasium  temperature   humidity        ph  \
0        90          42        43    20.879744  82.002744  6.502985   
1        85          58        41    21.770462  80.319644  7.038096   
2        60          55        44    23.004459  82.320763  7.840207   
3        74          35        40    26.491096  80.158363  6.980401   
4        78          42        42    20.130175  81.604873  7.628473   

     rainfall label  
0  202.935536  rice  
1  226.655537  rice  
2  263.964248  rice  
3  242.864034  rice  
4  262.717340  rice

In [5]:
#shape
data.shape

(2200, 8)

In [6]:
data.columns

Index(['nitrogen', 'phosphorus', 'potasium', 'temperature', 'humidity', 'ph',
       'rainfall', 'label'],
      dtype='object')

In [7]:
data.head()

nitrogen  phosphorus  potasium  temperature   humidity        ph  \
0        90          42        43    20.879744  82.002744  6.502985   
1        85          58        41    21.770462  80.319644  7.038096   
2        60          55        44    23.004459  82.320763  7.840207   
3        74          35        40    26.491096  80.158363  6.980401   
4        78          42        42    20.130175  81.604873  7.628473   

     rainfall label  
0  202.935536  rice  
1  226.655537  rice  
2  263.964248  rice  
3  242.864034  rice  
4  262.717340  rice

In [9]:
df=data.dropna()

In [10]:
df.shape

(2200, 8)

In [11]:
df.columns

Index(['nitrogen', 'phosphorus', 'potasium', 'temperature', 'humidity', 'ph',
       'rainfall', 'label'],
      dtype='object')

In [12]:
df.describe()

nitrogen   phosphorus     potasium  temperature     humidity  \
count  2200.000000  2200.000000  2200.000000  2200.000000  2200.000000   
mean     50.551818    53.362727    48.149091    25.616244    71.481779   
std      36.917334    32.985883    50.647931     5.063749    22.263812   
min       0.000000     5.000000     5.000000     8.825675    14.258040   
25%      21.000000    28.000000    20.000000    22.769375    60.261953   
50%      37.000000    51.000000    32.000000    25.598693    80.473146   
75%      84.250000    68.000000    49.000000    28.561654    89.948771   
max     140.000000   145.000000   205.000000    43.675493    99.981876   

                ph     rainfall  
count  2200.000000  2200.000000  
mean      6.469480   103.463655  
std       0.773938    54.958389  
min       3.504752    20.211267  
25%       5.971693    64.551686  
50%       6.425045    94.867624  
75%       6.923643   124.267508  
max       9.935091   298.560117

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   nitrogen     2200 non-null   int64  
 1   phosphorus   2200 non-null   int64  
 2   potasium     2200 non-null   int64  
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object 
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB


In [14]:
#Checking for duplicate data
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
2195    False
2196    False
2197    False
2198    False
2199    False
Length: 2200, dtype: bool

In [15]:
#find sum of duplicate data
sum(df.duplicated())

0

In [16]:
#Checking sum of missing values
df.isnull().sum()

nitrogen       0
phosphorus     0
potasium       0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [17]:
df.columns

Index(['nitrogen', 'phosphorus', 'potasium', 'temperature', 'humidity', 'ph',
       'rainfall', 'label'],
      dtype='object')

In [18]:
df.nitrogen.unique()

array([ 90,  85,  60,  74,  78,  69,  94,  89,  68,  91,  93,  77,  88,
        76,  67,  83,  98,  66,  97,  84,  73,  92,  95,  99,  63,  62,
        64,  82,  79,  65,  75,  71,  72,  70,  86,  61,  81,  80, 100,
        87,  96,  40,  23,  39,  22,  36,  32,  58,  59,  42,  28,  43,
        27,  50,  25,  31,  26,  54,  57,  49,  46,  38,  35,  52,  44,
        24,  29,  20,  56,  37,  51,  41,  34,  30,  33,  47,  53,  45,
        48,  13,   2,  17,  12,   6,  10,  19,  11,  18,  21,  16,   9,
         1,   7,   8,   0,   3,   4,   5,  14,  15,  55, 105, 108, 118,
       101, 106, 109, 117, 114, 110, 112, 111, 102, 116, 119, 107, 104,
       103, 120, 113, 115, 133, 136, 126, 121, 129, 122, 140, 131, 135,
       123, 125, 139, 132, 127, 130, 134], dtype=int64)

In [19]:
df.phosphorus.unique()

array([ 42,  58,  55,  35,  37,  53,  54,  46,  56,  50,  48,  38,  45,
        40,  59,  41,  47,  49,  51,  57,  39,  43,  44,  60,  52,  36,
        72,  67,  73,  70,  62,  74,  66,  63,  71,  78,  80,  68,  65,
        77,  76,  79,  61,  64,  69,  75,  24,  18,  26,  27,  25,  21,
        30,  11,   5,  10,   7,  20,  22,  15,  23,   8,  16,  29,  17,
         6,  19,  13,   9,  14,  28,  94,  95,  92,  89,  88,  87,  85,
        86,  83,  91,  81,  84,  90,  82,  93,  33,  31,  34,  32, 130,
       144, 123, 125, 131, 140, 122, 134, 145, 139, 141, 138, 136, 132,
       133, 121, 126, 120, 142, 135, 129, 128, 137, 127, 124, 143,  12],
      dtype=int64)

In [20]:
df.potasium.unique()

array([ 43,  41,  44,  40,  42,  38,  36,  37,  39,  35,  45,  16,  17,
        21,  20,  19,  25,  22,  15,  18,  23,  24,  77,  84,  85,  81,
        75,  79,  76,  83,  78,  80,  82,  46,  50,  53,  54,  49,  55,
        52,  47,  48,  51,  27,  31,  32,  34,  33,  30,  28,  29,  26,
       195, 204, 205, 196, 198, 197, 203, 201, 202, 199, 200,  12,  13,
         6,   9,  10,  14,   8,   7,   5,  11], dtype=int64)

In [21]:
df.potasium.sort_values().unique()

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85, 195, 196, 197,
       198, 199, 200, 201, 202, 203, 204, 205], dtype=int64)

In [22]:
p.Categorical(df['label']).describe()

counts     freqs
categories                   
apple           100  0.045455
banana          100  0.045455
blackgram       100  0.045455
chickpea        100  0.045455
coconut         100  0.045455
coffee          100  0.045455
cotton          100  0.045455
grapes          100  0.045455
jute            100  0.045455
kidneybeans     100  0.045455
lentil          100  0.045455
maize           100  0.045455
mango           100  0.045455
mothbeans       100  0.045455
mungbean        100  0.045455
muskmelon       100  0.045455
orange          100  0.045455
papaya          100  0.045455
pigeonpeas      100  0.045455
pomegranate     100  0.045455
rice            100  0.045455
watermelon      100  0.045455

In [23]:
df['label'].value_counts()

rice           100
maize          100
jute           100
cotton         100
coconut        100
papaya         100
orange         100
apple          100
muskmelon      100
watermelon     100
grapes         100
mango          100
banana         100
pomegranate    100
lentil         100
blackgram      100
mungbean       100
mothbeans      100
pigeonpeas     100
kidneybeans    100
chickpea       100
coffee         100
Name: label, dtype: int64

In [24]:
df['potasium'].value_counts()

17    90
22    87
15    86
20    80
25    78
      ..
5      8
11     8
13     7
7      5
80     4
Name: potasium, Length: 73, dtype: int64

In [25]:
df.corr()

nitrogen  phosphorus  potasium  temperature  humidity        ph  \
nitrogen     1.000000   -0.231460 -0.140512     0.026504  0.190688  0.096683   
phosphorus  -0.231460    1.000000  0.736232    -0.127541 -0.118734 -0.138019   
potasium    -0.140512    0.736232  1.000000    -0.160387  0.190859 -0.169503   
temperature  0.026504   -0.127541 -0.160387     1.000000  0.205320 -0.017795   
humidity     0.190688   -0.118734  0.190859     0.205320  1.000000 -0.008483   
ph           0.096683   -0.138019 -0.169503    -0.017795 -0.008483  1.000000   
rainfall     0.059020   -0.063839 -0.053461    -0.030084  0.094423 -0.109069   

             rainfall  
nitrogen     0.059020  
phosphorus  -0.063839  
potasium    -0.053461  
temperature -0.030084  
humidity     0.094423  
ph          -0.109069  
rainfall     1.000000

In [26]:
df.head()

nitrogen  phosphorus  potasium  temperature   humidity        ph  \
0        90          42        43    20.879744  82.002744  6.502985   
1        85          58        41    21.770462  80.319644  7.038096   
2        60          55        44    23.004459  82.320763  7.840207   
3        74          35        40    26.491096  80.158363  6.980401   
4        78          42        42    20.130175  81.604873  7.628473   

     rainfall label  
0  202.935536  rice  
1  226.655537  rice  
2  263.964248  rice  
3  242.864034  rice  
4  262.717340  rice

In [27]:
df.columns

Index(['nitrogen', 'phosphorus', 'potasium', 'temperature', 'humidity', 'ph',
       'rainfall', 'label'],
      dtype='object')

In [28]:
df['label'].unique()

array(['rice', 'maize', 'chickpea', 'kidneybeans', 'pigeonpeas',
       'mothbeans', 'mungbean', 'blackgram', 'lentil', 'pomegranate',
       'banana', 'mango', 'grapes', 'watermelon', 'muskmelon', 'apple',
       'orange', 'papaya', 'coconut', 'cotton', 'jute', 'coffee'],
      dtype=object)

In [29]:
from sklearn.preprocessing import LabelEncoder
var_mod = ['label']
le = LabelEncoder()
for i in var_mod:
    df[i] = le.fit_transform(df[i]).astype(int)

In [30]:
df['label'].unique()

array([20, 11,  3,  9, 18, 13, 14,  2, 10, 19,  1, 12,  7, 21, 15,  0, 16,
       17,  4,  6,  8,  5])

In [31]:
df.head(10)

nitrogen  phosphorus  potasium  temperature   humidity        ph  \
0        90          42        43    20.879744  82.002744  6.502985   
1        85          58        41    21.770462  80.319644  7.038096   
2        60          55        44    23.004459  82.320763  7.840207   
3        74          35        40    26.491096  80.158363  6.980401   
4        78          42        42    20.130175  81.604873  7.628473   
5        69          37        42    23.058049  83.370118  7.073454   
6        69          55        38    22.708838  82.639414  5.700806   
7        94          53        40    20.277744  82.894086  5.718627   
8        89          54        38    24.515881  83.535216  6.685346   
9        68          58        38    23.223974  83.033227  6.336254   

     rainfall  label  
0  202.935536     20  
1  226.655537     20  
2  263.964248     20  
3  242.864034     20  
4  262.717340     20  
5  251.055000     20  
6  271.324860     20  
7  241.974195     20  
8  230.446236     20  
9  221.209196     20

In [32]:
df.isnull().sum()

nitrogen       0
phosphorus     0
potasium       0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [33]:
df.tail(10)

nitrogen  phosphorus  potasium  temperature   humidity        ph  \
2190       103          40        30    27.309018  55.196224  6.348316   
2191       118          31        34    27.548230  62.881792  6.123796   
2192       106          21        35    25.627355  57.041511  7.428524   
2193       116          38        34    23.292503  50.045570  6.020947   
2194        97          35        26    24.914610  53.741447  6.334610   
2195       107          34        32    26.774637  66.413269  6.780064   
2196        99          15        27    27.417112  56.636362  6.086922   
2197       118          33        30    24.131797  67.225123  6.362608   
2198       117          32        34    26.272418  52.127394  6.758793   
2199       104          18        30    23.603016  60.396475  6.779833   

        rainfall  label  
2190  141.483164      5  
2191  181.417081      5  
2192  188.550654      5  
2193  183.468585      5  
2194  166.254931      5  
2195  177.774507      5  
2196  127.924610      5  
2197  173.322839      5  
2198  127.175293      5  
2199  140.937041      5